# Generated by Django 3.2.9 on 2021-11-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfoACodeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_create_time', models.DateTimeField(auto_now_add=True)),
                ('db_modify_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'akshare_stock_info_a_code_name',
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_create_time', models.DateTimeField(auto_now_add=True)),
                ('db_modify_time', models.DateTimeField(auto_now=True)),
                ('stock_id', models.CharField(max_length=10, unique=True)),
                ('market_symbol', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'akshare_stock_list',
            },
        ),
    ]
